###
GET http://34.51.209.130:13000

###
POST http://34.51.209.130:13000
Content-Type: application/json

{
    "name":"james",
    "location":"23 hellow world street"
}

###
GET http://localhost:3000/setup